# -*- coding: utf-8 -*-
"""20191639_math_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YctspOyS9hZ9ompnMTFDV10-5_R9JShc
"""

import copy
import random

# 1. 행렬 입력 함수
def input_matrix():
    mode = input("행렬을 직접 입력하려면 D, 랜덤 생성하려면 R을 입력하세요: ").strip().upper()
    n = int(input("정방행렬의 크기 n을 입력하세요: "))

    if mode == "R":
        # -5 ~ 5 범위의 정수 랜덤 생성
        matrix = [[random.randint(-5, 5) for _ in range(n)] for _ in range(n)]
        print(f"\n자동 생성된 {n}x{n} 랜덤 행렬:")
        for row in matrix:
            print(row)
        return matrix
    else:
        print(f"{n}x{n} 행렬의 원소를 행 단위로 입력하세요 (공백으로 구분):")
        matrix = []
        for i in range(n):
            row = list(map(float, input().split()))
            if len(row) != n:
                raise ValueError("입력한 원소 개수가 행렬 크기와 맞지 않습니다.")
            matrix.append(row)
        return matrix

# 2. 행렬식 계산 함수 (재귀적 Laplace 전개)
def determinant(matrix):
    n = len(matrix)
    if n == 1:
        return matrix[0][0]
    if n == 2:
        return matrix[0][0]*matrix[1][1] - matrix[0][1]*matrix[1][0]

    det = 0
    for c in range(n):
        minor = [row[:c] + row[c+1:] for row in matrix[1:]]
        det += ((-1)**c) * matrix[0][c] * determinant(minor)
    return det

# 3. 역행렬 (행렬식/수반행렬 이용)
def inverse_by_determinant(matrix):
    n = len(matrix)
    det = determinant(matrix)
    if det == 0:
        raise ValueError("역행렬이 존재하지 않습니다 (det=0).")

    # 수반행렬 (cofactor 행렬의 전치)
    cofactors = []
    for r in range(n):
        cofactor_row = []
        for c in range(n):
            minor = [row[:c] + row[c+1:] for i,row in enumerate(matrix) if i != r]
            cofactor_row.append(((-1)**(r+c)) * determinant(minor))
        cofactors.append(cofactor_row)

    # 전치
    cofactors_T = list(map(list, zip(*cofactors)))
    # 1/det 곱하기
    inverse = [[cofactors_T[r][c]/det for c in range(n)] for r in range(n)]
    return inverse

# 4. 역행렬 (가우스-조던 소거법)
def inverse_by_gauss_jordan(matrix):
    n = len(matrix)
    A = copy.deepcopy(matrix)
    I = [[float(i==j) for j in range(n)] for i in range(n)]

    for i in range(n):
        # 피벗 선택
        pivot = A[i][i]
        if pivot == 0:
            raise ValueError("가우스-조던 실패: 피벗이 0입니다.")

        # 피벗을 1로 만들기
        for j in range(n):
            A[i][j] /= pivot
            I[i][j] /= pivot

        # 다른 행에서 피벗 열 제거
        for k in range(n):
            if k != i:
                factor = A[k][i]
                for j in range(n):
                    A[k][j] -= factor * A[i][j]
                    I[k][j] -= factor * I[i][j]

    return I

# 5. 결과 출력 및 비교
def print_matrix(M):
    for row in M:
        print(" ".join(f"{val:8.4f}" for val in row))
    print()

def main():
    matrix = input_matrix()

    print("\n입력 행렬:")
    print_matrix(matrix)

    det = determinant(matrix)
    print(f"행렬식(det) = {det:.4f}\n")

    if det == 0:
        print("역행렬이 존재하지 않습니다.")
        return

    inv1 = inverse_by_determinant(matrix)
    inv2 = inverse_by_gauss_jordan(matrix)

    print("역행렬 (행렬식/수반행렬 이용):")
    print_matrix(inv1)

    print("역행렬 (가우스-조던 소거법 이용):")
    print_matrix(inv2)

    # 결과 비교
    same = all(abs(inv1[i][j] - inv2[i][j]) < 1e-6
                for i in range(len(matrix)) for j in range(len(matrix)))
    if same:
        print("두 방법의 결과가 동일합니다.")
    else:
        print("두 방법의 결과가 다릅니다.")

# 실행
if __name__ == "__main__":
    main()